image: docker.artifactory.globoi.com/cluster/sonar-scanner:3.2.0-py

stages:
  - test

test:
  stage: test
  script:
    - virtualenv .env
    - source .env/bin/activate
    - make install
    - export GOOGLE_APPLICATION_CREDENTIALS=./tests/mock/mock_credentials.json
    - make sonar
